### ISSUE TITLE
Cannot authorize the app, yassirh.com uses expired ssl sertificate

### ISSUE THREAD

**Issue by dlussky** [yassirh/digitalocean-swimmer#72]
After authorizing application in DO interface, i get redirected to yassirh.com and get secure connection fail. It completely prevents me from using the application.

This is what desktop firefox thinks about the domain:

yassirh.com uses an invalid security certificate. 
The certificate expired on September 17, 2017, 1:54 AM. 
The current time is September 19, 2017, 5:54 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by yassirh** [comment]
Hello I didn't get to change the certificate. I will do it asap!

**Comment by yassirh** [comment]
The issue has been fixed! Sorry for the inconvenience.

**Comment by Gradergage** [comment]
The problem is still relevant
![image](https://user-images.githubusercontent.com/8627307/45718109-a0b44700-bba4-11e8-970b-614fe836a9e8.png)

**Comment by vtolstov** [comment]
May be i miss something in oauth2 authorization, but why this app need external site to generate something?

**Comment by yassirh** [comment]
@Gradergage I will look into this later today. You can still generate the API key on Digitalocean's site and input it in the app meanwhile.
@vtolstov A redirect url is required to complete the flow : https://developers.digitalocean.com/documentation/oauth/

**Comment by vtolstov** [comment]
@yassirh as i know redirect uri - any uri , as you write android app, you can register handler for such uri in app. So when you authorize app you pass this uri and handle Location header in response with needed code and other data.

**Comment by vtolstov** [comment]
@yassirh check this https://www.oauth.com/oauth2-servers/mobile-and-native-apps/authorization/

**Comment by yassirh** [comment]
Indeed, now I remembre why... It is because there is a need for a client_secret that I can't share :) 

Do you have any work around it ?

**Comment by vtolstov** [comment]
You can use Client Application Flow with implicit authorization flow.
So you don't need to store client_secret on devices and in the app

**Comment by yassirh** [comment]
@vtolstov Indeed. It has been added recently to the documentation. I will look into it :) Thanks

**Comment by vtolstov** [comment]
@yassirh do you plan to fix this and not to use intermediate server for auth?

**Comment by yassirh** [comment]
Yes! I will fix this. a lot has changed since the last release and I want to do a major refactoring. It will surely be fixed then. Meanwhile, you can run your own server the files are included.

**Comment by vtolstov** [comment]
@yassirh when you want to release new app?
